name = "Minceraft S4"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "846e04574a4a7b675df78afdc8f1032af854f2f4e564d80ef6c67ed376eeda60"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
