name = "Minceraft S4"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59fe1e0c155630a4001c74d9d3c6e9c2e4ec74ddfe8404c335df47e061c09b8c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
