name = "Minceraft S4"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acab0dfa89cb9a78a3b527307e8ad099c1a5756be693ee1eb55d859cd69d5195"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
