name = "Minceraft S4"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7ec9c35b1b49a50a2463883213e0e3b3d68e7c6671b178fc1c7bc34bfd521d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
