name = "Minceraft S4"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "937a0bf9ea45d865f19c44bd1d5d6262f15b3e25925ba84ef808248273d3b7ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
