name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce263a5bfb9392c1c477443e3080dabbbbfb7039919f2e150b661c832674918e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
