name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68d30a61d9b670a195abbab753183439320088902772847c4cdabd87fcb3121c"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
