name = "Minceraft S3"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a782a585dd2bbb6551bcde6c940ff8a547cd00df1ed8158c7617d5e4c5ff1915"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
