name = "Minceraft"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbb9f9f9f01b0fda67f2d8679ae64f7d28a01a33677c1703db49d56228250801"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
